server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: aduana-api
          uri: http://aduana-api:8080
          predicates:
            - Path=/aduana/**
          filters:
            - RewritePath=/aduana/(?<remaining>.*), /${remaining}
        - id: usuarios-api
          uri: http://aduana-usuarios-api:8082
          predicates:
            - Path=/usuarios/**
          filters:
            - RewritePath=/usuarios/(?<remaining>.*), /${remaining}
        - id: reportes-api
          uri: http://aduana-reportes-api:8081
          predicates:
            - Path=/reportes/**
          filters:
            - RewritePath=/reportes/(?<remaining>.*), /${remaining}
          #RUTA NUEVA CREADA
        - id: documentos-api
          uri: http://aduana-api:8080
          predicates:
              - Path=/documentos/**
          filters:
              - RewritePath=/documentos/(?<remaining>.*), /api/v1/documentos/${remaining}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}